- project:
    queue: telemetry
    templates:
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
    check:
      jobs:
        - watcher-tempest-aetos:
            irrelevant-files: &irrelevant_files
              - ^\.gitignore$
              - ^\.gitreview$
              - ^\.pre-commit-config\.yaml$
              - ^test-requirements.txt$
              - ^doc/.*$
              - ^etc/.*$
              - ^.*\.rst$
              - ^releasenotes/.*$
              - ^aetos/tests/.*$
              - ^tox\.ini$
        - cloudkitty-tempest-full-v2-collector-aetos:
            irrelevant-files: *irrelevant_files
        - telemetry-dsvm-integration-aetos:
            irrelevant-files: *irrelevant_files
        - telemetry-dsvm-integration-aetos-ipv6-only:
            irrelevant-files: *irrelevant_files
    gate:
      jobs:
        - watcher-tempest-aetos:
            irrelevant-files: *irrelevant_files
        - cloudkitty-tempest-full-v2-collector-aetos:
            irrelevant-files: *irrelevant_files
        - telemetry-dsvm-integration-aetos:
            irrelevant-files: *irrelevant_files
        - telemetry-dsvm-integration-aetos-ipv6-only:
            irrelevant-files: *irrelevant_files
