- project:
    queue: telemetry
    templates:
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      # TODO(tkajinm): Enable this once ready
      #- release-notes-jobs-python3
      - check-requirements
